name: ask_qx
description: A new Flutter project.
publish_to: 'none'
version: 1.1.13+13

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  timeago: ^3.5.0 
  dio: ^5.3.0
  get: ^4.6.5
  google_fonts: ^4.0.5
  intl: ^0.18.1
  pinput: ^2.3.0
  image_picker: ^1.0.5
  get_storage: ^2.1.1
#  url_launcher: ^6.1.12
  loading_animation_widget: ^1.2.0+4
#  webview_flutter: ^4.4.3
  animated_text_kit: ^4.2.2
  speech_to_text: ^6.5.0
  flutter_tts: ^3.8.5
  animate_do: ^3.0.2
  share_plus: ^7.1.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^4.0.2
  lottie: ^2.6.0
#  advanced_in_app_review: ^1.1.3
  animated_toggle_switch: ^0.8.0
  flutter_animate: ^4.2.0+1
#  any_syntax_highlighter: ^0.0.13
  concentric_transition: ^1.0.3

  firebase_dynamic_links: 5.4.0
  firebase_remote_config: ^4.3.6
  firebase_analytics: 10.7.3
  firebase_messaging: ^14.7.6
  firebase_core: 2.24.1
  firebase_crashlytics: ^3.4.6
  flutter_local_notifications: ^16.2.0

#  flutter_expandable_fab: ^2.0.0
  google_sign_in: ^6.2.1
  signin_with_linkedin: ^1.0.0
#  facebook_app_events: ^0.19.0
  upgrader: ^9.0.0
  flutter_markdown: ^0.6.18+3
  adjust_sdk: ^4.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/jsons/

